name: CI

on:
  push:
    branches:
      - main
      - 'release/**'
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    permissions:
      contents: read
      packages: write
    uses: dgbarreto/stockapp-app/.github/workflows/kmp-module-ci.yml@main
    with:
      module: valuation
      use-konan-cache: false
    secrets:
      GH_PACKAGES_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
